when:
  branch: [main, staging]
steps:
  build:
    image: ghcr.io/xhain-hackspace/website-build-container:latest
    commands: |
      mkdir -p data
      first_date=$(date +%Y-%m-01)
      first_date_ms=$(date -d "$first_date" +%s)
      last_date=$(date -d "`date +%Y%m01` +1 month -1 day" +%Y-%m-%d)
      last_date_ms=$(date -d "$last_date" +%s)

      curl -s "https://files.x-hain.de/remote.php/dav/public-calendars/Yi63cicwgDnjaBHR/?export&accept=jcal&start=$first_date_ms&end=$last_date_ms&expand=1" -o temp.json
      if [ $? -eq 0 ]; then
          echo "Data fetched successfully."
      else
          echo "Error fetching data."
          exit 1
      fi

      jq ".[2][][1] | map({key:.[0], value:.[3]}) | from_entries" temp.json | jq -s > data/calendar.json
      if [ $? -eq 0 ]; then
          echo "Data transformed successfully."
      else
          echo "Error processing data."
          exit 1
      fi

      hugo version
      hugo -d public_html --config config.toml,home.toml --cleanDestinationDir --baseURL https://staging.x-hain.de
    when:
      event: [push, tag, deployment, cron, manual]
      branch: [main]

  build-staging:
    image: ghcr.io/xhain-hackspace/website-build-container:latest
    commands:
      - |
        mkdir -p data
        first_date=$(date +%Y-%m-01)
        first_date_ms=$(date -d "$first_date" +%s)
        last_date=$(date -d "`date +%Y%m01` +1 month -1 day" +%Y-%m-%d)
        last_date_ms=$(date -d "$last_date" +%s)

        curl -s "https://files.x-hain.de/remote.php/dav/public-calendars/Yi63cicwgDnjaBHR/?export&accept=jcal&start=$first_date_ms&end=$last_date_ms&expand=1" -o temp.json
        if [ $? -eq 0 ]; then
            echo "Data fetched successfully."
        else
            echo "Error fetching data."
            exit 1
        fi

        jq ".[2][][1] | map({key:.[0], value:.[3]}) | from_entries" temp.json | jq -s > data/calendar.json
        if [ $? -eq 0 ]; then
            echo "Data transformed successfully."
        else
            echo "Error processing data."
            exit 1
        fi

        hugo version
        hugo -d public_html --config config.toml,home.toml --cleanDestinationDir
    when:
      event: [push, tag, deployment]
      branch: [staging]

  deploy:
    image: drillster/drone-rsync
    settings:
      hosts: [x-hain.de]
      source: ./public_html/
      exclude: _
      target: /public
      delete: true
      recursive: true
      user:
        from_secret: SSH_USER
      key:
        from_secret: SSH_PRIVATE_KEY
    when:
      event: [push, tag, deployment, cron, manual]
      branch: [main]

  deploy_staging:
    image: drillster/drone-rsync
    settings:
      hosts: [staging.x-hain.de]
      source: ./public_html/
      exclude: _
      target: /public
      delete: true
      recursive: true
      user:
        from_secret: SSH_USER_STAGING
      key:
        from_secret: SSH_PRIVATE_KEY_STAGING
    when:
      event: [push, tag, deployment]
      branch: [staging]

  build-preview:
    image: ghcr.io/xhain-hackspace/website-build-container:latest
    commands: |
      mkdir -p data
      first_date=$(date +%Y-%m-01)
      first_date_ms=$(date -d "$first_date" +%s)
      last_date=$(date -d "`date +%Y%m01` +1 month -1 day" +%Y-%m-%d)
      last_date_ms=$(date -d "$last_date" +%s)

      curl -s "https://files.x-hain.de/remote.php/dav/public-calendars/Yi63cicwgDnjaBHR/?export&accept=jcal&start=$first_date_ms&end=$last_date_ms&expand=1" -o temp.json
      if [ $? -eq 0 ]; then
          echo "Data fetched successfully."
      else
          echo "Error fetching data."
          exit 1
      fi

      jq ".[2][][1] | map({key:.[0], value:.[3]}) | from_entries" temp.json | jq -s > data/calendar.json
      if [ $? -eq 0 ]; then
          echo "Data transformed successfully."
      else
          echo "Error processing data."
          exit 1
      fi

      hugo version
      hugo -d public_html --config config.toml,home.toml --cleanDestinationDir --baseURL /
    when:
      event: pull_request
  preview:
    image: woodpeckerci/plugin-surge-preview:next
    settings:
      path: ./public_html
      surge_token:
        from_secret: SURGE_TOKEN
      forge_type: github
      forge_url: https://github.com
      forge_repo_token:
        from_secret: GITHUB_TOKEN
    when:
      event: pull_request
