when:
  branch: [main, staging]
steps:
  build:
    image: ghcr.io/xhain-hackspace/website-build-container:v0.0.2
    commands:
      - ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
      - python3 download_calendar.py
      - hugo version
      - hugo -d public_html --config config.toml,home.toml --cleanDestinationDir
    when:
      event: [push, tag, deployment, cron, manual]
      branch: [main]

  build-staging:
    image: ghcr.io/xhain-hackspace/website-build-container:v0.0.2
    commands:
      - ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
      - python3 download_calendar.py
      - hugo version
      - hugo -d public_html --config config.toml,home.toml --cleanDestinationDir --baseURL https://staging.x-hain.de
    when:
      event: [push, tag, deployment]
      branch: [staging]

  deploy:
    image: drillster/drone-rsync
    settings:
      hosts: [x-hain.de]
      source: ./public_html/
      exclude: _
      target: /public
      delete: true
      recursive: true
      user:
        from_secret: SSH_USER
      key:
        from_secret: SSH_PRIVATE_KEY
    when:
      event: [push, tag, deployment, cron, manual]
      branch: [main]

  deploy_staging:
    image: drillster/drone-rsync
    settings:
      hosts: [staging.x-hain.de]
      source: ./public_html/
      exclude: _
      target: /public
      delete: true
      recursive: true
      user:
        from_secret: SSH_USER_STAGING
      key:
        from_secret: SSH_PRIVATE_KEY_STAGING
    when:
      event: [push, tag, deployment]
      branch: [staging]

  build-preview:
    image: ghcr.io/xhain-hackspace/website-build-container:v0.0.2
    commands:
      - ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
      - python3 download_calendar.py
      - hugo version
      - hugo -d public_html --config config.toml,home.toml --cleanDestinationDir --baseURL /
    when:
      event: pull_request
  preview:
    image: woodpeckerci/plugin-surge-preview:next
    settings:
      path: ./public_html
      surge_token:
        from_secret: SURGE_TOKEN
      forge_type: github
      forge_url: https://github.com
      forge_repo_token:
        from_secret: GITHUB_TOKEN
    when:
      event: pull_request
