# xHain Calendar Backend Configuration

# Server settings
server:
  port: 8080
  host: "0.0.0.0"
  static_content: "../public_html"

# Calendar settings
calendar:
  url: "https://files.x-hain.de/remote.php/dav/public-calendars/Yi63cicwgDnjaBHR"
  cache_ttl_minutes: 5
  months_to_show: 3

# Logging
logging:
  level: "info"
  format: "text" 
